package telas;

import beans.Produto;
import beans.Usuario;
import beans.Venda;
import beans.VendaProduto;
import dao.ProdutoDAO;
import dao.UsuarioDAO;
import dao.VendaDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;

public class FormTelaVenda extends javax.swing.JFrame {

    private int status;

    /**
     * Creates new form FormTelaVenda
     */
    public FormTelaVenda() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtVendaData = new javax.swing.JTextField();
        txtVendaProdutos = new javax.swing.JTextField();
        txtVendaID = new javax.swing.JTextField();
        txtVendaVendedor = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtVendaTotal = new javax.swing.JTextField();
        btnVMenu = new javax.swing.JButton();
        btnNovaVenda = new javax.swing.JButton();
        btnVendaCadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Nerko One", 0, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(69, 69, 122));
        jLabel1.setText("Ateliê do Tricô");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas/Imagem Atelie do Trico.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Livvic", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(45, 49, 116));
        jLabel3.setText("Data:");

        jLabel5.setFont(new java.awt.Font("Livvic Black", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(45, 49, 116));
        jLabel5.setText("Cadastro da venda");

        jLabel4.setFont(new java.awt.Font("Livvic", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(45, 49, 116));
        jLabel4.setText("ID:");

        jLabel6.setFont(new java.awt.Font("Livvic", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(45, 49, 116));
        jLabel6.setText("Vendedor:");

        txtVendaData.setBackground(new java.awt.Color(204, 204, 204));
        txtVendaData.setFont(new java.awt.Font("Livvic", 0, 18)); // NOI18N
        txtVendaData.setBorder(null);

        txtVendaProdutos.setBackground(new java.awt.Color(204, 204, 204));
        txtVendaProdutos.setFont(new java.awt.Font("Livvic", 0, 18)); // NOI18N
        txtVendaProdutos.setBorder(null);

        txtVendaID.setBackground(new java.awt.Color(204, 204, 204));
        txtVendaID.setFont(new java.awt.Font("Livvic", 0, 18)); // NOI18N
        txtVendaID.setBorder(null);

        txtVendaVendedor.setBackground(new java.awt.Color(204, 204, 204));
        txtVendaVendedor.setFont(new java.awt.Font("Livvic", 0, 18)); // NOI18N
        txtVendaVendedor.setBorder(null);

        jLabel8.setFont(new java.awt.Font("Livvic", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(45, 49, 116));
        jLabel8.setText("Produtos:");

        jLabel10.setFont(new java.awt.Font("Livvic", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(45, 49, 116));
        jLabel10.setText("Total:");

        txtVendaTotal.setBackground(new java.awt.Color(204, 204, 204));
        txtVendaTotal.setFont(new java.awt.Font("Livvic", 0, 18)); // NOI18N
        txtVendaTotal.setBorder(null);

        btnVMenu.setBackground(new java.awt.Color(53, 53, 110));
        btnVMenu.setFont(new java.awt.Font("Livvic", 0, 18)); // NOI18N
        btnVMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnVMenu.setText("Menu");
        btnVMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVMenuActionPerformed(evt);
            }
        });

        btnNovaVenda.setBackground(new java.awt.Color(53, 53, 110));
        btnNovaVenda.setFont(new java.awt.Font("Livvic", 0, 18)); // NOI18N
        btnNovaVenda.setForeground(new java.awt.Color(255, 255, 255));
        btnNovaVenda.setText("Novo venda");
        btnNovaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaVendaActionPerformed(evt);
            }
        });

        btnVendaCadastrar.setBackground(new java.awt.Color(53, 53, 110));
        btnVendaCadastrar.setFont(new java.awt.Font("Livvic", 0, 18)); // NOI18N
        btnVendaCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btnVendaCadastrar.setText("Cadastrar");
        btnVendaCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendaCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(65, 65, 65)
                                        .addComponent(btnVendaCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                                        .addComponent(btnNovaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(36, 36, 36))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel10)
                                        .addGap(5, 5, 5)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnVMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtVendaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel3))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(4, 4, 4)
                                        .addComponent(txtVendaID, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtVendaVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                                    .addComponent(txtVendaData)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtVendaProdutos)))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(txtVendaData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtVendaID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtVendaVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtVendaProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(txtVendaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVMenu)
                    .addComponent(btnNovaVenda)
                    .addComponent(btnVendaCadastrar))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVendaCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendaCadastrarActionPerformed
        try {

            if (txtVendaData.getText().trim().isEmpty()
                    || txtVendaVendedor.getText().trim().isEmpty()
                    || txtVendaTotal.getText().trim().isEmpty()
                    || txtVendaProdutos.getText().trim().isEmpty()) {

                JOptionPane.showMessageDialog(this, "Preencha todos os campos obrigatórios.", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }

            String dataVenda = txtVendaData.getText().trim();
            int idVendedor = Integer.parseInt(txtVendaVendedor.getText().trim());
            double totalVenda = Double.parseDouble(txtVendaTotal.getText().trim());

            Venda venda = new Venda();
            venda.setDataVenda(dataVenda);
            venda.setTotalVenda(totalVenda);

            UsuarioDAO usuarioDAO = new UsuarioDAO();
            Usuario vendedor = usuarioDAO.buscarUsuarioPorId(idVendedor);
            if (vendedor == null) {
                JOptionPane.showMessageDialog(this, "Vendedor não encontrado.", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }
            venda.setVendedorVenda(vendedor);

            List<VendaProduto> listaProdutos = new ArrayList<>();
            String[] produtosArray = txtVendaProdutos.getText().trim().split(",");

            ProdutoDAO produtoDAO = new ProdutoDAO();
            for (String idProduto : produtosArray) {
                int id = Integer.parseInt(idProduto.trim());
                Produto produto = produtoDAO.buscarProdutoPorId(id);

                if (produto != null) {

                    String quantidadeStr = JOptionPane.showInputDialog(this, "Quantidade para o produto ID " + id + ":", "1");
                    if (quantidadeStr != null && !quantidadeStr.trim().isEmpty()) {
                        int quantidade = Integer.parseInt(quantidadeStr.trim());

                        VendaProduto vendaProduto = new VendaProduto();
                        vendaProduto.setProdutoId(produto);
                        vendaProduto.setQuantidade(quantidade);
                        listaProdutos.add(vendaProduto);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Produto com ID " + id + " não encontrado.", "Erro", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            venda.setProdutosVenda(listaProdutos);

            VendaDAO vendaDAO = new VendaDAO();
            int status = vendaDAO.cadastrarVenda(venda);

            if (status > 0) {
                JOptionPane.showMessageDialog(this, "Venda cadastrada com sucesso!");
                btnNovaVendaActionPerformed(evt);
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao cadastrar venda.", "Erro", JOptionPane.ERROR_MESSAGE);
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Erro: Certifique-se de preencher os campos numéricos corretamente.", "Erro", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar venda: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnVendaCadastrarActionPerformed

    private void btnNovaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaVendaActionPerformed
        txtVendaData.setText("");
        txtVendaID.setText("");
        txtVendaProdutos.setText("");
        txtVendaTotal.setText("");
        txtVendaVendedor.setText("");

        txtVendaData.requestFocus();

    }//GEN-LAST:event_btnNovaVendaActionPerformed

    private void btnVMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVMenuActionPerformed
        FormTelaMenu menu = new FormTelaMenu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTelaVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNovaVenda;
    private javax.swing.JButton btnVMenu;
    private javax.swing.JButton btnVendaCadastrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtVendaData;
    private javax.swing.JTextField txtVendaID;
    private javax.swing.JTextField txtVendaProdutos;
    private javax.swing.JTextField txtVendaTotal;
    private javax.swing.JTextField txtVendaVendedor;
    // End of variables declaration//GEN-END:variables
}
