package telas;

import beans.Produto;
import dao.ProdutoDAO;
import javax.swing.JOptionPane;

public class FormTelaCadastro extends javax.swing.JFrame {

    private int status;

    /**
     * Creates new form FormTelaCadastro
     */
    public FormTelaCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtProdutoData = new javax.swing.JTextField();
        txtProdutoDescricao = new javax.swing.JTextField();
        txtProdutoID = new javax.swing.JTextField();
        txtProdutoQtd = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtProdutoPvenda = new javax.swing.JTextField();
        txtProdutoPCusto = new javax.swing.JTextField();
        btnPMenu = new javax.swing.JButton();
        btnNovoProduto = new javax.swing.JButton();
        btnProdutoCadastrar = new javax.swing.JButton();
        txtProdutoNome = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Nerko One", 0, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(69, 69, 122));
        jLabel1.setText("Ateliê do Tricô");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas/Imagem Atelie do Trico.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Livvic", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(45, 49, 116));
        jLabel3.setText("Data:");

        jLabel5.setFont(new java.awt.Font("Livvic Black", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(45, 49, 116));
        jLabel5.setText("Cadastro de Produto");

        jLabel4.setFont(new java.awt.Font("Livvic", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(45, 49, 116));
        jLabel4.setText("ID:");

        jLabel6.setFont(new java.awt.Font("Livvic", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(45, 49, 116));
        jLabel6.setText("Quantidade:");

        jLabel7.setFont(new java.awt.Font("Livvic", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(45, 49, 116));
        jLabel7.setText("Nome:");

        txtProdutoData.setBackground(new java.awt.Color(204, 204, 204));
        txtProdutoData.setFont(new java.awt.Font("Livvic", 0, 18)); // NOI18N
        txtProdutoData.setBorder(null);

        txtProdutoDescricao.setBackground(new java.awt.Color(204, 204, 204));
        txtProdutoDescricao.setFont(new java.awt.Font("Livvic", 0, 18)); // NOI18N
        txtProdutoDescricao.setBorder(null);

        txtProdutoID.setBackground(new java.awt.Color(204, 204, 204));
        txtProdutoID.setFont(new java.awt.Font("Livvic", 0, 18)); // NOI18N
        txtProdutoID.setBorder(null);

        txtProdutoQtd.setBackground(new java.awt.Color(204, 204, 204));
        txtProdutoQtd.setFont(new java.awt.Font("Livvic", 0, 18)); // NOI18N
        txtProdutoQtd.setBorder(null);

        jLabel8.setFont(new java.awt.Font("Livvic", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(45, 49, 116));
        jLabel8.setText("Descrição:");

        jLabel9.setFont(new java.awt.Font("Livvic", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(45, 49, 116));
        jLabel9.setText("Preço de custo:");

        jLabel10.setFont(new java.awt.Font("Livvic", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(45, 49, 116));
        jLabel10.setText("Preço de Venda:");

        txtProdutoPvenda.setBackground(new java.awt.Color(204, 204, 204));
        txtProdutoPvenda.setFont(new java.awt.Font("Livvic", 0, 18)); // NOI18N
        txtProdutoPvenda.setBorder(null);

        txtProdutoPCusto.setBackground(new java.awt.Color(204, 204, 204));
        txtProdutoPCusto.setFont(new java.awt.Font("Livvic", 0, 18)); // NOI18N
        txtProdutoPCusto.setBorder(null);

        btnPMenu.setBackground(new java.awt.Color(53, 53, 110));
        btnPMenu.setFont(new java.awt.Font("Livvic", 0, 18)); // NOI18N
        btnPMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnPMenu.setText("Menu");
        btnPMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPMenuActionPerformed(evt);
            }
        });

        btnNovoProduto.setBackground(new java.awt.Color(53, 53, 110));
        btnNovoProduto.setFont(new java.awt.Font("Livvic", 0, 18)); // NOI18N
        btnNovoProduto.setForeground(new java.awt.Color(255, 255, 255));
        btnNovoProduto.setText("Novo produto");
        btnNovoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoProdutoActionPerformed(evt);
            }
        });

        btnProdutoCadastrar.setBackground(new java.awt.Color(53, 53, 110));
        btnProdutoCadastrar.setFont(new java.awt.Font("Livvic", 0, 18)); // NOI18N
        btnProdutoCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btnProdutoCadastrar.setText("Cadastrar");
        btnProdutoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutoCadastrarActionPerformed(evt);
            }
        });

        txtProdutoNome.setBackground(new java.awt.Color(204, 204, 204));
        txtProdutoNome.setFont(new java.awt.Font("Livvic", 0, 18)); // NOI18N
        txtProdutoNome.setBorder(null);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                            .addGap(65, 65, 65)
                                            .addComponent(btnProdutoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(62, 62, 62)
                                            .addComponent(btnNovoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtProdutoPCusto, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel10)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtProdutoPvenda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                            .addComponent(btnPMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(22, 22, 22))))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtProdutoData, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(4, 4, 4)
                                    .addComponent(txtProdutoNome))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(4, 4, 4)
                                    .addComponent(txtProdutoID, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtProdutoQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtProdutoDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(txtProdutoData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtProdutoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtProdutoQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtProdutoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtProdutoDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(txtProdutoPvenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProdutoPCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPMenu)
                    .addComponent(btnNovoProduto)
                    .addComponent(btnProdutoCadastrar))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnProdutoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutoCadastrarActionPerformed
        try {
            String nomeProduto = txtProdutoNome.getText().trim();
            String dataProduto = txtProdutoData.getText().trim();
            String descricaoProduto = txtProdutoDescricao.getText().trim();
            int qtdProduto = Integer.parseInt(txtProdutoQtd.getText().trim());
            double precoCustoProduto = Double.parseDouble(txtProdutoPCusto.getText().trim());
            double precoVendaProduto = Double.parseDouble(txtProdutoPvenda.getText().trim());

            if (nomeProduto.isEmpty() || dataProduto.isEmpty() || descricaoProduto.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Preencha todos os campos obrigatórios.", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Produto produto = new Produto();
            produto.setNomeProduto(nomeProduto);
            produto.setDataProduto(dataProduto);
            produto.setDescricaoProduto(descricaoProduto);
            produto.setQtdProduto(qtdProduto);
            produto.setPrecoCustoProduto(precoCustoProduto);
            produto.setPrecoVendaProduto(precoVendaProduto);

            ProdutoDAO produtoDAO = new ProdutoDAO();
            int status = produtoDAO.cadastrarProduto(produto); // Captura o retorno do método

            if (status > 0) {
                JOptionPane.showMessageDialog(this, "Produto cadastrado com sucesso!");

            } else {
                JOptionPane.showMessageDialog(this, "Erro ao cadastrar produto.", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Erro: Certifique-se de preencher os campos numéricos corretamente.", "Erro", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar produto: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnProdutoCadastrarActionPerformed

    private void btnNovoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoProdutoActionPerformed
        txtProdutoID.setText("");
        txtProdutoNome.setText("");
        txtProdutoData.setText("");
        txtProdutoDescricao.setText("");
        txtProdutoQtd.setText("");
        txtProdutoPCusto.setText("");
        txtProdutoPvenda.setText("");

        txtProdutoNome.requestFocus();
    }//GEN-LAST:event_btnNovoProdutoActionPerformed

    private void btnPMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPMenuActionPerformed
        FormTelaMenu menu = new FormTelaMenu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTelaCadastro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTelaCadastro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTelaCadastro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTelaCadastro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNovoProduto;
    private javax.swing.JButton btnPMenu;
    private javax.swing.JButton btnProdutoCadastrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtProdutoData;
    private javax.swing.JTextField txtProdutoDescricao;
    private javax.swing.JTextField txtProdutoID;
    private javax.swing.JTextField txtProdutoNome;
    private javax.swing.JTextField txtProdutoPCusto;
    private javax.swing.JTextField txtProdutoPvenda;
    private javax.swing.JTextField txtProdutoQtd;
    // End of variables declaration//GEN-END:variables
}
